# - name: Sync scripts/data folder
#   hosts: sp25-cs525-1202.cs.illinois.edu
#   tasks:
#     - name: Rsync data
#       ansible.posix.synchronize:
#         src: "../../tests/data/Pacific_Rim"
#         dest: "/home/sj99/360Torrent/tests/data/Pacific_Rim"
#         recursive: yes

---
- name: Delete project directories from /home/sj99
  hosts: peers  # Change to 'peers', 'WA', etc. as needed
  gather_facts: no

  tasks:
    - name: Remove ~/Data
      ansible.builtin.file:
        path: /home/sj99/360Torrent/tests/data/
        state: absent

    - name: Recreate ~/360Torrent/tests/data
      ansible.builtin.file:
        path: /home/sj99/360Torrent/tests/data/
        state: directory
        mode: '0755'
    
    # - name: Remove all video folders except video0
    #   ansible.builtin.shell: |
    #     find /home/sj99/360Torrent/tests/data_warehouse -mindepth 1 -maxdepth 1 -type d ! -name "video0" -exec rm -rf {} +
    #   args:
    #     executable: /bin/bash

    # # STEP 4: Move and rename chunk01.webm → chunk.webm in data_warehouse
    # - name: Move and rename chunk01.webm to chunk.webm
    #   ansible.builtin.shell: |
    #     mv /home/sj99/360Torrent/tests/data_warehouse/video0/chunk01.webm /home/sj99/360Torrent/tests/data_warehouse/chunk.webm
    #   args:
    #     executable: /bin/bash

  

    # - name: Remove ~/app
    #   ansible.builtin.file:
    #     path: /home/sj99/app
    #     state: absent

    # - name: Remove ~/myenv
    #   ansible.builtin.file:
    #     path: /home/sj99/myenv
    #     state: absent

    # - name: Clone Git repo into ~/360Torrent
    #   ansible.builtin.git:
    #     repo: https://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@github.com/sjain166/360Torrent.git  # 🔁 Replace this
    #     dest: /home/sj99/360Torrent
    #     clone: yes
    #     update: yes