---
- name: Download peer.log files from all peers
  hosts: peers
  gather_facts: no

  tasks:
    - name: Extract vm index and register filename
      ansible.builtin.shell: |
        echo "vm$(hostname | grep -oP '\d{4}' | awk '{printf "%02d", $1 - 1200}').log"
      register: vm_log_name
      changed_when: false

    - name: Fetch peer.log and save as vmXX.log locally
      ansible.builtin.fetch:
        src: /home/sj99/360Torrent/tests/peer.log
        dest: "../../tests/logs/{{ vm_log_name.stdout }}"
        flat: yes


- name: Download tracker.log from tracker
  hosts: tracker
  gather_facts: no

  tasks:
    - name: Fetch tracker.log and save it locally
      ansible.builtin.fetch:
        src: /home/sj99/360Torrent/tests/tracker.log
        dest: "../../tests/logs/tracker.log"
        flat: yes