# fetch_tracker_log.yml
- name: Download tracker log file to local machine
  hosts: tracker
  gather_facts: no

  tasks:
    - name: Fetch tracker.log from remote to local
      ansible.builtin.fetch:
        src: /home/sj99/360Torrent/tests/tracker.log
        dest: ../../tests/logs/  # Local path on your machine
        flat: yes