- name: Download peer.log files from all peers
  hosts: all
  gather_facts: no

  tasks:
    - name: Extract vm index and register filename
      ansible.builtin.shell: |
        echo "vm$(hostname | grep -oP '\d{4}' | awk '{printf "%02d", $1 - 1200}').log"
      register: vm_log_name
      changed_when: false

    - name: Fetch peer.log and save as vmXX.log locally
      ansible.builtin.fetch:
        src: /home/sj99/360Torrent/tests/peer.log
        dest: "../../tests/logs/{{ vm_log_name.stdout }}"
        flat: yes

    - name: Fetch tracker.log from remote to local
      ansible.builtin.fetch:
        src: /home/sj99/360Torrent/tests/tracker.log
        dest: ../../tests/logs/  # Local path on your machine
        flat: yes