# install_dstat.yml
- name: Install dstat on all VMs
  hosts: all
  become: true
  tasks:
    - name: Install dstat
      apt:
        name: dstat
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install dstat (RedHat-based systems)
      yum:
        name: dstat 
        state: present
      when: ansible_facts['os_family'] == "RedHat"