- name: Pull Repo and install dependencies
  hosts: all
  become: false
  gather_facts: no

  tasks:
    - name: Pull latest code from Git
      shell: git pull
      args:
        chdir: /home/sj99/360Torrent

    - name: Install Python dependencies from requirements.txt
      shell: |
        source myenv/bin/activate
        pip install -r requirements.txt
      args:
        chdir: /home/sj99/360Torrent
        executable: /bin/bash

# ansible-playbook -i hosts.ini pull_repo.yml



