- name: Pull Repo
  hosts: all
  become: false
  tasks:

    - name: Pull in /home/sj99/360Torrent
      shell: git pull
      args:
        chdir: /home/sj99/360Torrent

# ansible-playbook -i hosts.ini pull_repo.yml



