- name: Launch peer inside tmux
  hosts: peers
  gather_facts: no

  tasks:

      - name: Delete existing peer.log if it exists
        ansible.builtin.file:
            path: /home/sj99/360Torrent/tests/peer.log
            state: absent

      - name: Delete existing summary.json if it exists
        ansible.builtin.file:
            path: /home/sj99/360Torrent/tests/summary.json
            state: absent
            
      - name: Kill existing tmux session if it exists
        shell: tmux kill-session -t peer_session || true
        ignore_errors: true
          
      - name: Start peer in tmux
        shell: |
          tmux new-session -d -s peer_session 'cd /home/sj99/360Torrent && source myenv/bin/activate && python3 -m peer.peer RND >> /home/sj99/360Torrent/tests/peer.log 2>&1'
        args:
          executable: /bin/bash

# ansible-playbook -i hosts.ini start_peer.yml
# ssh user@peer_vm
# tmux attach-session -t peer_session
# tmux attach-session -t tracker_session

# TERMINATES ALl VMs
# ansible all -i hosts.ini -a "tmux kill-session -t peer_session"