# - name: Launch tracker inside tmux
#   hosts: tracker
#   tasks:
#     - name: Start tracker in tmux
#       shell: |
#         tmux new-session -d -s tracker_session 'cd /home/sj99/360Torrent && source myenv/bin/activate && python3 -m tracker.tracker'

- name: Launch tracker inside tmux
  hosts: tracker
  gather_facts: no

  tasks:
      - name: Delete existing tracker.log if it exists
        ansible.builtin.file:
            path: /home/sj99/360Torrent/tests/tracker.log
            state: absent
      
      - name: Delete existing summary.json if it exists
        ansible.builtin.file:
            path: /home/sj99/360Torrent/tests/summary.json
            state: absent
            
      - name: Kill existing tmux session if it exists
        shell: tmux kill-session -t tracker_session || true
        ignore_errors: true
      
      - name: Start tracker in tmux with logging
        shell: |
          tmux new-session -d -s tracker_session 'cd /home/sj99/360Torrent && source myenv/bin/activate && python3 -m tracker.tracker GF >> /home/sj99/360Torrent/tests/tracker.log 2>&1'
        args:
          executable: /bin/bash


# ansible-playbook -i hosts.ini start_tracker.yml
# ssh user@peer_vm
# tmux attach-session -t start_tracker