- name: Launch peer inside tmux
  hosts: peers
  tasks:
    - name: Start tracker in tmux
      shell: |
        tmux new-session -d -s peer_session 'cd /home/sj99/app && source myenv/bin/activate && python3 -m peer.peer'

# ansible-playbook -i hosts.ini start_peer.yml
# ssh user@peer_vm
# tmux attach-session -t peer_session

# TERMINATES ALl VMs
# ansible all -i hosts.ini -a "tmux kill-session -t peer_session"